name: 自动部署

on:
  push:
    branches:
      - main 

  release:
    types:
      - published

  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 检查分支
      uses: actions/checkout@main
      with:
        ref: main
    
    - name: 安装最新版 Golang
      uses: actions/setup-go@v7
      with:
        go-version: 'stable'

    - name: 检测Golang环境版本
      run: |
        go version

    - name: 安装 Node
      uses: actions/setup-node@v7
      with:
        node-version: 'lts/*'

    - name: 安装 Hexo 及 压缩插件
      run: |
        npm install hexo-cli --global

    - name: 安装依赖
      run: |
        npm install --save

    - name: 检测 Node 版本
      run: |
        node -v

    - name: 检测 npm 版本
      run: |
        npm -v

    - name: 检测 Hexo 版本
      run: |
        hexo -v

    - name: 清理文件树
      run: |
        npm run clean
        hexo cl

    - name: 生成静态文件
      run: |
        hexo g 

    - name: 压缩文件
      run: |
        npm install terser html-minifier-terser postcss cssnano sharp svgo glob fast-glob
        node min.js public

    - name: 部署
      run: |
        cd ./public
        git init
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git add .
        git commit -m "${{ github.event.head_commit.message }}··[$(date +"%Z %Y-%m-%d %A %H:%M:%S")]"
        git push --force --quiet "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}" master:refs/heads/page
